services:
  postgres:
    image: postgres:16.3-alpine3.20
    container_name: postgresql
    volumes:
      - postgres:/var/lib/postgresql
      - ./database:/docker-entrypoint-initdb.d # load database script
    ports:                               
      - "5432:5432"
    environment:   
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: neoris
    networks:
      - neoris

  zoo:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.6.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    networks:
      - neoris
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.6.1
    depends_on:
      - zoo
    ports:
      - 29092:29092
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zoo:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - neoris

  ms-customer-domain:
    container_name: ms-customer-domain
    build:
      context: ./ms-customer-domain
      dockerfile: Dockerfile
    image: ms-customer-domain:latest
    environment:
      - server.port=8080
      - spring_datasource_url=jdbc:postgresql://postgres:5432/neoris
      - spring_datasource_username=admin
      - spring_datasource_password=admin
      - spring.kafka.bootstrap-servers=kafka:29092
      - spring.jpa.hibernate.ddl-auto=none
    ports:
      - "8080:8080"
    restart: always
    networks:
      - neoris
    depends_on:
      - postgres
      - kafka
  ms-account-domain:
    container_name: ms-account-domain
    build:
      context: ./ms-account-domain
      dockerfile: Dockerfile
    image: ms-account-domain:latest
    environment:
      - server.port=8081
      - spring_datasource_url=jdbc:postgresql://postgres:5432/neoris
      - spring_datasource_username=admin
      - spring_datasource_password=admin
      - spring.kafka.bootstrap-servers=kafka:9092
      - spring.jpa.hibernate.ddl-auto=none
    ports:
      - "8081:8081"
    restart: always
    networks:
      - neoris
    depends_on:
      - postgres
      - kafka
networks:
  neoris:
volumes:
  postgres: