services:
  postgres:
    image: postgres:16.3-alpine3.20
    container_name: postgresql
    volumes:
      - postgres:/var/lib/postgresql
    ports:                               
      - "5432:5432"
    environment:   
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: neoris
    networks:
      - neoris
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin4_container
  #   restart: always
  #   ports:
  #     - "8888:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
  #     PGADMIN_DEFAULT_PASSWORD: strong-password
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin
  zoo:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.6.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    networks:
      - neoris
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.6.1
    depends_on:
      - zoo
    ports:
      - 29092:29092
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zoo:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - neoris
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:v0.7.2
    depends_on:
      - kafka
    ports:
      - 8090:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zoo:2181
    networks:
      - neoris
#  ms-account-domain:
#    container_name: ms-account-domain
#    build:
#      context: ./ms-account-domain
#      dockerfile: Dockerfile
#    image: ms-account-domain:latest
#    environment:
#      - spring_datasource_url=jdbc:postgresql://postgres:5432/neoris
#      - spring_datasource_username=admin
#      - spring_datasource_password=admin
#    ports:
#      - "8081:8081"
#    restart: always
#    networks:
#      - neoris
#    depends_on:
#      - postgres
#      - kafka
networks:
  neoris:
volumes:
  postgres: